name = "Paraglyph"
description = "Music Producer"
keywords = "Music, Music Producer, Sound, Sound Design, Mixing, Mastering, Songs"
image = "Paraglyph Logo.png"
theme = "dark"
primary_color = "#ffbf00"
text_align = "center"
gtag_id = "GTM-55D6RKC6"
base_url = "https://gthgotohealth.github.io"
 

[[sections]]
title = "TuneCore - Single - Koi Bat De!"
description = "Links to the New Song"
direction = "row"
item_style = "filled"
icon_size = "30px"
hover_color = "#ffffff"

[[sections.items]]
icon = "https://cdn.simpleicons.org/googledocs/3f4436"
title = "Lyrics"
url = "https://docs.google.com/document/d/19mFMH9SPM1FVwgtHohoU66ic6j-U6CQ_wioP0WnBOSw/edit?tab=t.0"
text_color = "#3f4436" 

[[sections.items]]
icon = "https://cdn.simpleicons.org/youtube/3f4436"
title = "YouTube Audio"
url = "https://www.youtube.com/watch?v=8W1ONUxBLIM"
text_color = "#3f4436" 

[[sections.items]]
icon = "https://cdn.simpleicons.org/googledrive/3f4436"
title = "GDrive"
url = "https://drive.google.com/file/d/17hOuQYsgTW-Q_DUgXF03E6Q8azsHqTfg/view"
text_color = "#3f4436" 

[[sections.items]]
icon = "https://cdn.simpleicons.org/dropbox/3f4436"
title = "DropBox"
url = "https://www.dropbox.com/scl/fi/yvr8hnyufa4hkosvej5tc/Koi-Bata-De-Paraglyph-TF101.wav?rlkey=lw9wj52climuhbmn9wu5qb9j9&st=8o8xmhwi&dl=0"
text_color = "#3f4436" 

[[sections.items]]
icon = "https://cdn.simpleicons.org/bandlab/3f4436"
title = "BandLab"
url = "https://www.bandlab.com/revisions/c2d9dfdf-8de5-ef11-88f6-6045bd3473c0?sharedKey=Qeb9Nzh-MEavTMtlV5KF-Q"
text_color = "#3f4436" 


[[sections]]
title = "Social Media Profiles"
description = "Follow me on my Socials!"
direction = "row"
item_style = "filled"
icon_size = "30px"
hover_color = "#ffffff"

[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/3f4436"
title = "Instagram"
url = "https://www.instagram.com/theparaglyph?igsh=MXExYncxaWthMmZyeg%3D%3D&utm_source=qr"
text_color = "#3f4436" 

[[sections.items]]
icon = "https://cdn.simpleicons.org/youtube/3f4436"
title = "YouTube"
url = "https://youtube.com/@theparaglyph?si=GFCeFq_4Wdqfa0Sg"
text_color = "#3f4436" 

[[sections.items]]
icon = "https://cdn.simpleicons.org/spotify/3f4436"
title = "Spotify"
url = "https://open.spotify.com/artist/01183I1kKHm1VrSPHNctn9?si=ycobF75nQ8qQhEAq7nTigA"
text_color = "#3f4436" 

[[sections.items]]
icon = "https://cdn.simpleicons.org/applemusic/3f4436"
title = "Apple Music"
url = "https://music.apple.com/us/playlist/evergreen/pl.7d5e4029dd9140ffbb5da5fda64b3f02"
text_color = "#3f4436" 



